### ISSUE TITLE
Whitespace around inline elements are not preserved

### ISSUE THREAD

**Issue by madskristensen** [xoofx/NUglify#4]
Consider this input HTML:

```html
<!DOCTYPE html> 
<html> 
<head> 
    <meta charset="utf-8" /> 
    <title></title>
</head> 
<body> 
    <span>Some</span> 
    <span>whitespace</span> 
</body> 
</html>
```

It is being minified to this:

```html
<!DOCTYPE html><html><head><meta charset=utf-8><title></title></head><body><span>Some</span><span>whitespace</span></body></html>
```

Notice that there is no whitespace around the `<span>` tags. An option for maintaining a single whitespace (space char) would be great.

**Comment by xoofx** [comment]
Thanks for the report! This was somewhat a bug, as the collapse on whitespace was only running inside phrasing elements (like surround by `<p>`), so I removed this restriction and it should be fixed by commit 7764a697391945e628ded0c605681de62464439b. The nuget 1.4.3 is being built

**Comment by madskristensen** [comment]
Awesome. Thanks :)

**Comment by IlBaffo** [comment]
Hi, I've been having problems with whitespace collapsing lately and the "CollapseWhitespaces" option is quite extreme for me because it totally removes whitespace and, with empty tags (compiled at runtime by javascript), this becomes problematic.

Example
=
Take for instance this code
```
<style>
.a:before { color: white; background: red; content: "a" }
.b:before { color: white; background: green; content: "b" }
.c:before { color: white; background: blue; content: "c" }
</style>
<div>
<span class="a"></span>
<span class="b"></span>
<span class="c"></span>
</div>
<div>
	<span class="a"></span>          <span class="b"></span>        <span class="c"></span>
</div>
```
This, at runtime is displayed as
![image](https://cloud.githubusercontent.com/assets/7044910/19519181/1124712a-960b-11e6-8e32-14842a600865.png)

When minified, white spaces are removed totally
`<div><span class=a></span><span class=b></span><span class=c></span></div><div><span class=a></span><span class=b></span><span class=c></span></div>`

And this is the result
![image](https://cloud.githubusercontent.com/assets/7044910/19519218/4952ec34-960b-11e6-80b1-5a9bbb9c0592.png)

Proposed change
=
I think that this option should respect the HTML spec in the sense that multiple whitespaces (or newlines, or tabs) are considered as one by the browsers http://www.w3.org/TR/html401/struct/text.html#whitespace (except for pre, textarea, ... and elements with white-space css rules) so newlines/tabs/spaces sould be collapsed to exactly one space, like this:
`<div> <span class=a></span> <span class=b></span> <span class=c></span> </div> <div> <span class=a></span> <span class=b></span> <span class=c></span> </div>`
Wich will preserve rendering fidelity.

Proposed implementation
=
So I would suggest to add another option (in addition to the first one) named "CollapseWhitespacesMode" with either ["removeAll", "collapseToOne"] or similar values with "removeAll" as a default (for retro-compatibility).

white-space css rules
-
I don't think this is solvable because css are seldom injected or changed at runtime so it is impossible to detect if one should keep white-space, at this regard, the only suggestion I have is to use a special comment (like linters use to disable some rule) to preserve white space in specific portions of the file like `<!-- nuglify:CollapseWhitespaces:false --><html><!-- nuglify:CollapseWhitespaces:true -->`.

**Comment by xoofx** [comment]
@IlBaffo there is a new HtmlSettings.KeepOneSpaceWhenCollapsing option added to commit df0fca6

**Comment by IlBaffo** [comment]
Thank you very much.
